# Loan Approval Prediction Configuration

# Data Configuration
data:
  raw_data_path: "loan_approval_dataset.csv"
  processed_data_path: "results/processed_data.csv"
  test_size: 0.2
  validation_size: 0.15
  random_state: 42

# Feature Configuration
features:
  categorical_features:
    - "education"
    - "self_employed"
  numerical_features:
    - "no_of_dependents"
    - "income_annum"
    - "loan_amount"
    - "loan_term"
    - "cibil_score"
    - "residential_assets_value"
    - "commercial_assets_value"
    - "luxury_assets_value"
    - "bank_asset_value"
  target_column: "loan_status"
  id_column: "loan_id"

# Preprocessing Configuration
preprocessing:
  missing_value_strategy:
    numerical: "median"
    categorical: "most_frequent"
  scaling_method: "standard"  # standard, minmax, robust
  encoding_method: "onehot"   # onehot, label

# Class Imbalance Configuration
imbalance:
  apply_smote: true
  smote_sampling_strategy: "auto"
  smote_k_neighbors: 5
  alternative_methods:
    - "RandomOverSampler"
    - "ADASYN"

# Model Configuration
models:
  logistic_regression:
    hyperparameters:
      C: [0.1, 1.0, 10.0, 100.0]
      penalty: ["l1", "l2"]
      solver: ["liblinear", "saga"]
      max_iter: [1000]
    
  decision_tree:
    hyperparameters:
      max_depth: [5, 10, null]
      min_samples_split: [2, 10]
      min_samples_leaf: [1, 4]
      criterion: ["gini", "entropy"]
  
  random_forest:
    hyperparameters:
      n_estimators: [100, 200, 300]
      max_depth: [5, 10, 15, null]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]

# Evaluation Configuration
evaluation:
  cv_folds: 5
  scoring_metrics:
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  primary_metric: "f1"  # For model selection
  
# Production Configuration
production:
  model_save_path: "models/"
  api_host: "0.0.0.0"
  api_port: 8000
  log_level: "INFO"
  model_version: "v1.0"

# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  file_path: "logs/loan_prediction.log"
